version: '3'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-database-data:/var/lib/postgresql/data
    networks:
      - kong-net
    restart: always

  kong:
    image: kong:3.1
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_PORT: 5432
      KONG_PORT: 8000
      KONG_ADMIN_PORT: 8001
    ports:
      - "8000:8000"  # Port untuk API Gateway
      - "8001:8001"  # Port untuk Admin API
    depends_on:
      - kong-database
    networks:
      - kong-net
    restart: always

  kong-migrations:
    image: kong:3.1
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    networks:
      - kong-net
    restart: "no"

networks:
  kong-net:
    driver: bridge

volumes:
  kong-database-data:
    driver: local