version: '3'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-database-data:/var/lib/postgresql/data
    networks:
      - kong-net
    restart: always

  kong:
    image: kong:3.1
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_PORT: 5432
      KONG_PORT: 8000           # HTTP port untuk API Gateway
      KONG_HTTPS_PORT: 8443     # HTTPS port untuk API Gateway
      KONG_ADMIN_PORT: 8444     # Admin API port (HTTPS)
      KONG_ADMIN_LISTEN: 0.0.0.0:8444 ssl  # Enable Admin API di port 8444 dengan HTTPS
      KONG_ADMIN_GUI_HOST: kong.parahyangandigital.cloud
      KONG_ADMIN_GUI_PROTOCOL: https  # Gunakan HTTPS untuk Admin GUI
      KONG_SSL_CERT: /etc/ssl/certs/fullchain.pem  # Path ke sertifikat SSL
      KONG_SSL_CERT_KEY: /etc/ssl/private/privkey.pem  # Path ke private key SSL
      KONG_CONF: /etc/kong/kong.conf  # Tentukan file konfigurasi Kong
    volumes:
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem
      - ./kong.conf:/etc/kong/kong.conf  # Pemetaan file konfigurasi kong.conf
    ports:
      - "8000:8000"  # Port untuk HTTP API Gateway (opsional)
      - "8443:8443"  # Port untuk HTTPS API Gateway (opsional)
      - "8444:8444"  # Port untuk Admin API dengan HTTPS
    depends_on:
      - kong-database
    networks:
      - kong-net
    restart: always

  kong-migrations:
    image: kong:3.1
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    networks:
      - kong-net
    restart: "no"

networks:
  kong-net:
    driver: bridge

volumes:
  kong-database-data:
    driver: local
